export const JOB_ID = {
  Frontend: 1,
  Backend: 2,
  Fullstack: 3,
  DevOps·SRE: 4,
  ML: 5,
  QA·TestEngineer: 6,
  Data: 7,
  Embedded: 8,
  Hardware: 9,
  WebPublisher: 10,
  Security: 11,
  Designer: 12,
  TechnicalWriter: 13,
  System·NetworkEngineer: 14,
  SAP·ERP·MES: 15,
  'Android·iOS·CrossPlatform': 16,
  DBA: 17,
  Others: 99,
} as const;

// 소문자 기준으로 키워드를 찾으며, [' ', '.', '-', '_']는 무시된다.
export const JOB_KEYWORD = {
  Frontend: [
    'frontend',
    'react',
    'vue',
    'next',
    'nuxt',
    '프론트엔드',
    '프론트앤드',
    '프런트엔드',
    '프런트앤드',
  ],
  Backend: [
    'backend',
    'spring',
    'nest',
    'fastapi',
    'django',
    'server',
    '백엔드',
    '백앤드',
    '서버',
  ],
  Fullstack: ['fullstack', 'webdevelop', '풀스택', '웹개발'],
  'DevOps·SRE': ['devops', 'sre', 'sitereliability', '데브옵스'],
  ML: ['ml', 'machinlearning', '머신러닝'],
  QA·TestEngineer: ['qa', 'testengineer', '테스트'],
  Data: [
    'data',
    'bi',
    'da',
    'de',
    'analyst',
    'businessintelligence',
    '데이터',
    '분석',
  ],
  Embedded: ['embedded', '임베디드'],
  Hardware: ['hardware', 'hw', '하드웨어'],
  WebPublisher: ['publisher', 'publishing', '퍼블리서', '퍼블리셔', '퍼블리싱'],
  Security: [
    'security',
    'endpoint',
    '보안',
    '관제',
    '해킹',
    '진단',
    '엔드포인트',
    '앤드포인트',
  ],
  Designer: [
    'designer',
    'artist',
    'animator',
    'ui',
    'ux',
    'modeling',
    '디자이너',
    '아티스트',
    '애니메이터',
    '모델링',
  ],
  TechnicalWriter: ['technicalwriter', '테크니컬라이터'],
  System·NetworkEngineer: [
    'systemengineer',
    'network',
    'idc',
    'cloud',
    '시스템엔지니어',
    '네트워크',
    '클라우드',
  ],
  SAP·ERP·MES: ['sap', 'erp', 'mes', '전사적자원관리'],
  Android·iOS·CrossPlatform: [
    'android',
    'ios',
    'reactnative',
    'flutter',
    'rn',
    '플러터',
    '안드로이드',
    '모바일',
  ],
  DBA: ['dba', 'database', '데이터베이스'],
  Others: [
    'it',
    'po',
    'pm',
    'productowner',
    'productmanager',
    'projectowner',
    'projectmanager',
    'engineer',
    'develop',
    'client',
    'ai',
    'tech',
    'cto',
    '프로덕트매니저',
    '프로덕트오너',
    '프로젝트오너',
    '프로젝트매니저',
    '엔지니어',
    '개발',
    '클라이언트',
    '테크',
  ],
} satisfies Record<keyof typeof JOB_ID, string[]>;

export const EMPLOYMENT_TYPE = {
  FULL_TIME: 1,
  CONTRACT: 2,
  INTERN: 3,
  MILITARY_ALTERNATIVE: 4,
} as const;
